# roles/k8s-node/tasks/swap.yml
- name: Disable swap immediately
  command: swapoff -a
  become: true

- name: Comment out swap line in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].* swap .*)$'
    replace: '# \1'
  become: true
